extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Lights1 castle_grounds_dl_F3D_Death_lights;
extern u8 castle_grounds_dl_ci4_anonmoose_Grass1_ci4[];
extern u8 castle_grounds_dl_ci4_anonmoose_Grass1_pal_rgba16[];
extern u8 castle_grounds_dl_ci4_anonmoose_Dirt1_ci8[];
extern u8 castle_grounds_dl_ci4_anonmoose_Dirt1_pal_rgba16[];
extern Vtx castle_grounds_dl_DeathPlane_mesh_layer_5_vtx_0[4];
extern Gfx castle_grounds_dl_DeathPlane_mesh_layer_5_tri_0[];
extern Vtx castle_grounds_dl_Ground_mesh_layer_1_vtx_0[116];
extern Gfx castle_grounds_dl_Ground_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Ground_mesh_layer_1_vtx_1[447];
extern Gfx castle_grounds_dl_Ground_mesh_layer_1_tri_1[];
extern Gfx mat_castle_grounds_dl_F3D_Death[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_002[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material_002[];
extern Gfx mat_castle_grounds_dl_f3dlite_material[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material[];
extern Gfx castle_grounds_dl_DeathPlane_mesh_layer_5[];
extern Gfx castle_grounds_dl_Ground_mesh_layer_1[];
extern Gfx castle_grounds_dl_material_revert_render_settings[];
