extern const GeoLayout bbh_area_1_geo[];
extern const GeoLayout bbh_area_1[];
extern const Collision bbh_area_1_collision[];
extern const MacroObject bbh_area_1_macro_objs[];
extern Lights1 bbh_dl_f3dlite_material_003_lights;
extern Lights1 bbh_dl_f3dlite_material_004_lights;
extern Lights1 bbh_dl_f3dlite_material_001_lights;
extern Lights1 bbh_dl_F3D_Death_lights;
extern Vtx bbh_dl_Ball_Pit_mesh_layer_1_vtx_0[40];
extern Gfx bbh_dl_Ball_Pit_mesh_layer_1_tri_0[];
extern Vtx bbh_dl_Ball_Pit_mesh_layer_1_vtx_1[469];
extern Gfx bbh_dl_Ball_Pit_mesh_layer_1_tri_1[];
extern Vtx bbh_dl_Ball_Pit_mesh_layer_1_vtx_2[128];
extern Gfx bbh_dl_Ball_Pit_mesh_layer_1_tri_2[];
extern Vtx bbh_dl_DeathPlane_mesh_layer_5_vtx_0[4];
extern Gfx bbh_dl_DeathPlane_mesh_layer_5_tri_0[];
extern Gfx mat_bbh_dl_f3dlite_material_003[];
extern Gfx mat_bbh_dl_f3dlite_material_004[];
extern Gfx mat_bbh_dl_f3dlite_material_001[];
extern Gfx mat_bbh_dl_F3D_Death[];
extern Gfx bbh_dl_Ball_Pit_mesh_layer_1[];
extern Gfx bbh_dl_DeathPlane_mesh_layer_5[];
extern Gfx bbh_dl_material_revert_render_settings[];
